version: '3'

services:
  db:
    build:
      context: ./mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3306:3306
    networks:
      default:
        aliases:
          - mysql-db-host

  php:
    build:
      context: ./php
      args:
        ORO_USER_ID: "${HOST_USER_ID:?err}"
        ORO_USER_GROUP_ID: "${HOST_USER_GROUP_ID:?err}"
    volumes:
      - ./www:/var/www
      - web-composer-cache:/home/oro/.composer
    ports:
      - "${WEBSOCKET_PUB_PORT?:err}:8080"
    networks:
      default:
        aliases:
          - php-fpm-host

  mail:
    image: mailhog/mailhog
    networks:
      default:
        aliases:
          - mailhog-host
    
  nginx:
    build:
      context: ./nginx
      args:
        ORO_USER_ID: "${HOST_USER_ID:?err}"
        ORO_USER_GROUP_ID: "${HOST_USER_GROUP_ID:?err}"
    volumes:
      - ./www:/var/www
    ports:
      - "${WEB_PUB_PORT?:err}:80"
    depends_on:
      - php
      - mail



volumes:
  mysql:
  web-composer-cache:

